name: 'CFBlog-Search.xml'

on:
  watch:
    types: started
  schedule:
    # 时间是按UTC设置的，实际执行时间，则自动按东八区执行
    # 即+8小时，故实际执行时间为：18点
    - cron: 0 10 * * *

jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    
    steps:
    - uses: actions/checkout@master
    - name: Get Search.xml
      env:
        CFBLOG_TOKEN: ${{ secrets.CFBLOG_TOKEN }}
      run: |
        git checkout -b search
        git checkout search
        curl 'https://blog.arrontg.cf/admin/search.xml' -H 'cfblog_token: '$CFBLOG_TOKEN'' >search.xml

    - name: commit change
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "action"
        git add .
        git commit -m "Update from Github Action"`date +%Y-%m-%d`
    - name: push change
      env:
        GITHUB_LOGIN: ${{ github.repository_owner }}
        GITHUB_TOKEN: ${{ github.token }}
        GITHUB_REPOSITORY: ${{ github.repository }}
      run: |
        git push https://$GITHUB_LOGIN:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git origin search
    - name: done
      run: echo 'done'
      
